<template>
  <div>

    <MaterialListings :buying="true"
                      :listings="listings">
    </MaterialListings>

  </div>
</template>

<script>
import MaterialListings from '@/components/material/MaterialListings'

export default {
  components: {
    MaterialListings
  },
  data () {
    return {
      perPage: 25,
      listings: [
        {
          id: 'gsh27dh7263',
          shape: 'w',
          dimension: '8x10',
          weight: 10,
          feet: 10,
          inches: 7,
          numerator: 7,
          denominator: 8,
          forSale: true,
          cwt: 42,
          grade: 'A992',
          heat: '593726718',
          quantity: 1,
          domestic: true,
          painted: false,
          galvanized: false,
          company: 'Benco Welding Inc.',
          city: 'Winder',
          state: 'GA',
          cut: true,
          cutPrice: 5,
          cutKerf: .125,
          delivery: true,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        },
        {
          id: 'gsh27dh7262',
          shape: 'w',
          dimension: '8x10',
          weight: 10,
          feet: 14,
          inches: 4,
          numerator: 3,
          denominator: 16,
          forSale: true,
          cwt: 36,
          grade: 'A992',
          heat: '',
          quantity: 3,
          domestic: true,
          painted: false,
          galvanized: false,
          company: 'AMD Welding',
          city: 'Winder',
          state: 'GA',
          cut: false,
          cutPrice: 5,
          cutKerf: .125,
          delivery: false,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        },
        {
          id: 'gsh27dh7264',
          shape: 'hss',
          dimension: '3x3x1/4',
          weight: 8.81,
          feet: 8,
          inches: 6,
          numerator: null,
          denominator: null,
          forSale: true,
          cwt: 48,
          grade: 'A500',
          heat: '593726718',
          quantity: 5,
          domestic: true,
          painted: true,
          galvanized: false,
          company: 'RAI',
          city: 'Athens',
          state: 'GA',
          cut: true,
          cutPrice: 5,
          cutKerf: .125,
          delivery: true,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        },
        {
          id: 'gsh27dh7265',
          shape: 'hss',
          dimension: '3 1/2 x 3 1/2 x 5/16',
          weight: 12.7,
          feet: 16,
          inches: 10,
          numerator: 15,
          denominator: 16,
          forSale: true,
          cwt: 39,
          grade: 'A36',
          heat: '593726718',
          quantity: 10,
          domestic: false,
          painted: false,
          galvanized: true,
          company: 'King Steel',
          city: 'Lawrenceville',
          state: 'GA',
          cut: true,
          cutPrice: 5,
          cutKerf: .125,
          delivery: true,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        },
        {
          id: 'gsh27dh7266',
          shape: 'c',
          dimension: '3x4.1',
          weight: 4.1,
          feet: 10,
          inches: 11,
          numerator: 7,
          denominator: 8,
          forSale: true,
          cwt: 45,
          grade: 'A36',
          heat: '593726718',
          quantity: 1,
          domestic: true,
          painted: true,
          galvanized: true,
          company: 'Benco Welding Inc.',
          city: 'Winder',
          state: 'GA',
          cut: true,
          cutPrice: 5,
          cutKerf: .125,
          delivery: true,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        },
        {
          id: 'gsh27dh7273',
          shape: 'w',
          dimension: '8x10',
          weight: 10,
          feet: 10,
          inches: 7,
          numerator: 7,
          denominator: 8,
          forSale: true,
          cwt: 42,
          grade: 'A992',
          heat: '593726718',
          quantity: 1,
          domestic: true,
          painted: false,
          galvanized: false,
          company: 'Benco Welding Inc.',
          city: 'Winder',
          state: 'GA',
          cut: true,
          cutPrice: 5,
          cutKerf: .125,
          delivery: true,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        },
        {
          id: 'gsh27dh7267',
          shape: 'w',
          dimension: '8x10',
          weight: 10,
          feet: 10,
          inches: 7,
          numerator: 7,
          denominator: 8,
          forSale: true,
          cwt: 42,
          grade: 'A992',
          heat: '593726718',
          quantity: 1,
          domestic: true,
          painted: false,
          galvanized: false,
          company: 'Benco Welding Inc.',
          city: 'Winder',
          state: 'GA',
          cut: true,
          cutPrice: 5,
          cutKerf: .125,
          delivery: true,
          deliveryMaxWeight: 2000,
          deliveryMaxLength: 20,
          deliveryPrice: 2,
          deliveryMaxDistance: 25
        }
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
  @import '@/assets/scss/variables.scss';
</style>
